name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}\.output
  DOTNET_VERSION: "3.1.*"
  # FUNCTION_NAME: "ImageResizeTask" # moved inside jobs to work with matrices

on:
  # Change to pull_request and 'main'
  push:
    branches:
      - none

jobs:
  tenantprep:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.set-matrix.outputs.config }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/StagingList.json) | sed 's/ //g')
          echo "::set-output name=config::$TASKS"

  testenv:
    run-on: windows-latest
    strategy:
      matrix: ${{ fromJson(needs.tenantprep.outputs.stag_config) }}
    environment: ${{ matrix.environment }}
    steps:
      run: echo "Hello"

  