name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}\.output
  DOTNET_VERSION: "3.1.*"
  # FUNCTION_NAME: "ImageResizeTask" # moved inside jobs to work with matrices

on:
  # Change to pull_request and 'main'
  push:
    branches:
      - none

jobs:
  tenantprep:
    runs-on: ubuntu-latest
    outputs:
      stag_config: ${{ steps.set-matrix.outputs.stag_config }}
      prod_config: ${{ steps.set-matrix.outputs.prod_config }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/StagingList.json) | sed 's/ //g')
          echo "::set-output name=stag_config::$TASKS"
          TASKS=$(echo $(cat .github/workflows/ProductionList.json) | sed 's/ //g')
          echo "::set-output name=prod_config::$TASKS"

  testenv:
    needs: [tenantprep]
    runs-on: windows-latest
    strategy:
      matrix: ${{ fromJson(needs.tenantprep.outputs.prod_config) }}
    environment: Production
    steps:
    - name: Run Pester
      shell: pwsh
      run: echo "Hello"


  