name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}\.output
  DOTNET_VERSION: "3.1.*"
  # FUNCTION_NAME: "ImageResizeTask" # moved inside jobs to work with matrices

on:
  # Change to pull_request and 'main'
  push:
    branches:
      - main

jobs:
  testenv:
    runs-on: windows-latest
    environment: Production
    steps:
    - name: Run Pester
      shell: pwsh
      run: echo "Hello"

  testenv2:
    needs: [testenv]
    runs-on: windows-latest
    environment: Production
    steps:
    - name: Run Pester
      shell: pwsh
      run: echo "Hello"

  