name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}\.output
  DOTNET_VERSION: "3.1.*"
  # FUNCTION_NAME: "ImageResizeTask" # moved inside jobs to work with matrices

on:
  # Change to pull_request and 'main'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.IMAGE_PAT }}
      
      - name: Setup Dotnet Env
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Publish Funcions
        shell: pwsh
        run: |
          get-childitem
          get-childitem -path .\TaskImageResize
          get-childitem -path .\TaskImageResize\src
          dotnet publish .TaskImageResize/src/TaskImageResize.csproj --configuration Release --output ${{ env.OUTPUT_PATH }}

      - name: Package Functions
        uses: actions/upload-artifact@v1 # find where the files go to.
        with:
          name: ImageResizeFunction
          path: ${{ env.OUTPUT_PATH }}
