name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}\.output
  DOTNET_VERSION: "3.1.*"
  # FUNCTION_NAME: "ImageResizeTask" # moved inside jobs to work with matrices

on:
  # Change to pull_request and 'main'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Get submodule hash
        run: |
          git --version


  