name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}\.output
  DOTNET_VERSION: "3.1.*"
  # FUNCTION_NAME: "ImageResizeTask" # moved inside jobs to work with matrices

on:
  # Change to pull_request and 'main'
  push:
    branches:
      - main

jobs:
  Pester:
    runs-on: windows-latest
    environment: Staging
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SUBA_AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Run Pester
        shell: pwsh
        run: | 
          $env:ResourceGroup = "igusp-suba-rg-fdzap"
          $env:StorageAccount = "iguspsubasavidiprocfdzap"
          $env:QueueName = "queue"
          $env:ContainerName = "videoprocess"
          Invoke-Pester ./DevOps/VideoProcess/PostDeploy.Tests.ps1 -passthru

  